# -*- coding: utf-8 -*-
"""DSBDA_PR9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_NdUXkqImGdlhqmoq7wRSkGui3Veee9t
"""

# 9) Data Visualization II
# 1. Use the inbuilt dataset 'titanic' as used in the above problem. Plot a box plot for
# distribution of age with respect to each gender along with the information about whether
# they survived or not. (Column names : 'sex' and 'age')
# 2. Write observations on the inference from the above statistics.

import seaborn as sns

import matplotlib.pyplot as plt
import pandas as pd

# Load the Titanic dataset
titanic = sns.load_dataset('titanic')

print(titanic.head())

titanic.describe()

sns.boxplot(x='sex', y='age', hue='survived', data=titanic)

# Create a boxplot for age distribution by sex and survival status
plt.figure(figsize=(10, 6))
plt.title('Age Distribution by Gender and Survival Status')
plt.xlabel('Gender')
plt.ylabel('Age')
sns.boxplot(x='sex', y='age', hue='survived', data=titanic)
plt.show()

#Observations from the Box Plot:

#Females generally had a higher survival rate compared to males.

# Young children (lower age group) among both males and females had a better chance of survival.

# Males had a wider spread of age and lower median survival age compared to females.

# Outliers are present, showing that some very old passengers survived or did not survive.

# Females who survived had a relatively younger median age compared to females who did not survive.

