# -*- coding: utf-8 -*-
"""DSBDA_PR3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pA6UO5gtRNYqfOS7TIKZrVgXFIiegGt0
"""

# 3) Descriptive Statistics - Measures of Central Tendency and variability
# Perform the following operations on any open-source dataset (e.g., data.csv)
# 1. Provide summary statistics (mean, median, minimum, maximum, standard deviation) for
# a dataset (age, income etc.) with numeric variables grouped by one of the qualitative
# (categorical) variable. For example, if your categorical variable is age groups and
# quantitative variable is income, then provide summary statistics of income grouped by the
# age groups. Create a list that contains a numeric value for each response to the categorical
# variable.
# 2. Write a Python program to display some basic statistical details like percentile, mean,
# standard deviation etc. of the species of ‘Iris-setosa’, ‘Iris-versicolor’ and ‘Iris-versicolor’ of
# iris.csv dataset.

import pandas as pd

data = {
    'Age_Group': ['18-25', '26-35', '18-25', '36-45', '26-35', '36-45', '18-25', '26-35', '36-45', '18-25'],
    'Income': [25000, 40000, 27000, 50000, 42000, 55000, 26000, 41000, 53000, 24000]
}

df = pd.DataFrame(data)

# Group by Age_Group and calculate summary statistics
summary_stats = df.groupby('Age_Group')['Income'].agg(['mean', 'median', 'min', 'max', 'std'])

# Print the summary statistics
print("Summary Statistics grouped by Age Group:")
print(summary_stats)

# Create a list for each Age Group containing all Income values
grouped_list = df.groupby('Age_Group')['Income'].apply(list).to_dict()

# Print the list
print("\nList of Income values for each Age Group:")
print(grouped_list)

import pandas as pd
from sklearn.datasets import load_iris

iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['species'] = pd.Categorical.from_codes(iris.target, iris.target_names)

# Filter for each species
setosa = df[df['species'] == 'setosa']
versicolor = df[df['species'] == 'versicolor']
virginica = df[df['species'] == 'virginica']

# Display basic statistics for 'setosa'
print("Setosa Statistics:")

print(setosa.describe())

# Display basic statistics for 'versicolor'
print("\nVersicolor Statistics:")
print(versicolor.describe())

# Display basic statistics for 'virginica'
print("\nVirginica Statistics:")
print(virginica.describe())

