# -*- coding: utf-8 -*-
"""DSBDA_PR10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MH8D6MifyOv12mSsdRGTVMYzfwHIjfvX
"""

# 10) Data Visualization III
# Download the Iris flower dataset or any other dataset into a DataFrame. (e.g.,
# https://archive.ics.uci.edu/ml/datasets/Iris ). Scan the dataset and give the inference as:
# 1. List down the features and their types (e.g., numeric, nominal) available in the dataset.
# 2. Create a histogram for each feature in the dataset to illustrate the feature distributions.
# 3. Create a boxplot for each feature in the dataset.
# 4. Compare distributions and identify outliers.

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# # 2. Load the Iris dataset
# from sklearn.datasets import load_iris

# Load the Iris dataset from a URL
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
column_names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']
iris = pd.read_csv(url, header=None, names=column_names)

# 1. List down the features and their types (e.g., numeric, nominal) available in the dataset.
print("Features and their types:")
print(iris.dtypes)

# 2. Create histograms for each feature
iris_features = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
iris[iris_features].hist(bins=20, figsize=(12, 10))
plt.suptitle('Histograms of Iris Features')
plt.show()

# 3. Create boxplots for each feature
plt.figure(figsize=(12, 8))
for i, feature in enumerate(iris_features, 1):
    plt.subplot(2, 2, i)
    sns.boxplot(data=iris, x='species', y=feature)
    plt.title(f'Boxplot for {feature}')
plt.tight_layout()
plt.show()

# # 4. Compare distributions and identify outliers
# # From the histograms, you can observe how each feature is distributed.
# # Boxplots help in identifying outliers, which are the points outside of the "whiskers".

# 1. Comparing Distributions:
# Histograms: From the histograms, you can observe how each feature is distributed. Typically:
# Normal Distribution: A bell-shaped curve (e.g., petal length) would suggest a normal distribution.
# Skewed Distribution: If one tail is longer, the feature is skewed. For example, if petal width shows
# a longer right tail, it might be positively skewed.
# Multi-modal Distribution: Multiple peaks can suggest the presence of different groups within the data
# (such as species), which might indicate a different distribution for each group.
# Distribution Characteristics: Histograms will give you a rough idea of the spread, skewness, and
# central tendency (mean/median) of each feature.

# 2. Identifying Outliers:
# Boxplots: Outliers can be identified in boxplots as points that fall outside the "whiskers"
# (i.e., 1.5 times the interquartile range above the upper quartile or below the lower quartile).
# Points outside this range are considered outliers.
# Outliers in Features: If you notice any data points that fall significantly above or below
# the boxplot's whiskers, these points are potential outliers. For example:
# Sepal Length: Might have outliers if there are a few extremely long or short sepals.
# Petal Width: If you see a single point far from the rest of the data, it could be an outlier
# (for instance, a very large petal width).
# By examining both histograms and boxplots together, you can:

# Histograms show the overall distribution, helping you see whether the feature is normally distributed,
# skewed, or multimodal.
# Boxplots help you identify outliers by highlighting points beyond the whiskers. These outliers
# # might need further investigation, as they can either represent anomalies or significant data points worth studying.

# Comparison and Outlier Identification:
# From the histograms, features like petal length and petal width show clear separation between species, while sepal width is more spread out.

# Boxplots reveal outliers mainly in the sepal width feature for all species.

# Setosa species shows less variability in petal measurements, while Versicolor and Virginica show overlapping distributions in some features.

# Outliers are the points lying outside the boxplot whiskers and indicate unusual measurements compared to the rest of the dataset.

